spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db20220622131603_high?TNS_ADMIN=/Users/kimmy/User2/Wallet_DB20220622131603
    username: admin
    password: eb1227eb!!KKK
